### ISSUE TITLE
Add default profile

### ISSUE THREAD

**Issue by gipert** [legend-exp/legend-dataflow#18]
Add file `profiles/default/config.yaml` with e.g. this:
```yaml
configfile: config.json
keep-going: true
rerun-incomplete: true

cores: all
```
There is then no need to specify the config file in the Snakemake command line. A simple `snakemake` call will work.
